config/routes.rb
Rails.application.routes.draw do
  get 'coins/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :coins
  resources :purchase_orders
  root 'coins#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
    def price
        Rails.cache.fetch(symbol, expires_in: 5.minutes) do
            begin
                response = RestClient.get 'https://min-api.cryptocompare.com/data/price', {params: {'fsym' => symbol, 'tsyms' => 'USD'}}
                JSON.parse(response)['USD']
            rescue => e
                0
            end
        end
    end
end

app/models/purchase_order.rb
class PurchaseOrder < ApplicationRecord
  belongs_to :coin
  def priceNow
    quantity * coin.price
  end

  validates :quantity, presence: true,
                       numericality: {greater_than: 0}
  validates :pricePaid, presence: true,
                        numericality: {greater_than: 0}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController

    def index
        @coins = Coin.all
    end

    def show
        @coin = Coin.find(params[:id])
    end

    def new
    end
end

app/controllers/purchase_orders_controller.rb
class PurchaseOrdersController < ApplicationController
    def index
        @purchaseOrders = PurchaseOrder.all
    end

    def new
        @purchaseOrder = PurchaseOrder.new quantity: 1,
                                           coin: Coin.find(params[:coin_id])
        @coin = @purchaseOrder.coin
    end

    def create
        #puts params[:coin].inspect
        @purchaseOrder = PurchaseOrder.new(params.require(:purchaseOrder).permit(:quantity))
        coin = Coin.find(params[:coin][:id]);
        @purchaseOrder.coin = coin
        @purchaseOrder.pricePaid = @purchaseOrder.priceNow
        if @purchaseOrder.save
            redirect_to @purchaseOrder
        else
            if coin.price == 0
                flash[:alert] = "Unnable to fetch coin price, please try again in a few minutes"
            else
                flash[:alert] = "You can't buy it for free ;)"
            end
            redirect_to action: "new",
                        coin_id: @purchaseOrder.coin.id
        end
    end

    def show
        @purchaseOrder = PurchaseOrder.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def active_if(options)
        if params.merge(options) == params
            'nav-active'
        end
    end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
end

app/views/coins/index.html.erb
<h1>Coins</h1>
<table>
  <tr>
    <th>Image</th>
    <th>Symbol</th>
    <th>Coin Name</th>
    <th>Price</th>
    <th>Link</th>
    <th>Buy</th>
  </tr>

  <% @coins.each do |coin| %>
    <tr>
      <td><img src="https://www.cryptocompare.com<%= coin.imageUrl %>"></td>
      <td><%= coin.symbol %></td>
      <td><%= coin.coinName %></td>
      <td>$ <%= coin.price %></td>
      <td><%= link_to 'Link', coin_path(coin) %></td>
      <td><%= link_to 'Buy', new_purchase_order_path(:coin_id => coin.id) %></td>
    </tr>
  <% end %>
</table>

app/views/coins/show.html.erb
<h1><img src="https://www.cryptocompare.com<%= @coin.imageUrl %>"> <%= @coin.coinName %> (<%= @coin.symbol %>)</h1>
<p>
  Current price: <span class="price">$ <%= @coin.price %></span> 
  <%= link_to 'Buy', new_purchase_order_path(:coin_id => @coin.id) %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptocurrencyPortfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <span class="app-title">Cryptocurrency</span>
      <nav>
        <ul class="menu">
          <li>
            <%= link_to 'Coins', coins_path , class: active_if(controller: 'coins')%>
          </li>
          <li>
            <%= link_to 'My Portfolio', purchase_orders_path, class: active_if(controller: 'purchase_orders') %>
          </li>
        </ul>
      </nav>
    </header>
    <span class="content">
      <% if flash[:alert] %>
        <span class="error"><%= flash[:alert] %></span>
      <% end %>
      <%= yield %>
    </span>
  </body>
</html>

app/views/purchase_orders/index.html.erb
<h1>My Portfolio</h1>
<table>
  <tr>
    <th>Order #</th>
    <th>Coin</th>
    <th>Quantity</th>
    <th>Price paid</th>
    <th>Price now</th>
    <th>Link</th>
  </tr>
 
  <% @purchaseOrders.each do |purchaseOrder| %>
    <tr>
      <td><%= purchaseOrder.id %></td>
      <td><img src="https://www.cryptocompare.com<%= purchaseOrder.coin.imageUrl %>"> <%= purchaseOrder.coin.coinName %> (<%= purchaseOrder.coin.symbol %>)</td>
      <td><%= purchaseOrder.quantity %></td>
      <td>$ <%= purchaseOrder.pricePaid %></td>
      <td class="<%= (purchaseOrder.pricePaid > purchaseOrder.priceNow)? 'lose' : 'win'  %>">$ <%= purchaseOrder.priceNow %></td>
      <td><%= link_to 'Link', purchase_order_path(purchaseOrder) %></td>
    </tr>
  <% end %>
</table>

app/views/purchase_orders/new.html.erb
<h1>Purchase Order</h1>
<%= form_with scope: :purchaseOrder, url: purchase_orders_path, local: true do |form| %>
  <table id="buy">
    <tr>
      <th>Coin</th>
      <th>Unit Price</th>
      <th><%= form.label :quantity %></th>
    </tr>
    <tr>
      <td>
        <img src="https://www.cryptocompare.com<%= @purchaseOrder.coin.imageUrl %>"> <%= @purchaseOrder.coin.coinName %> (<%= @purchaseOrder.coin.symbol %>)
      </td>
      <td>
        $ <span id="price"><%= @purchaseOrder.coin.price %></span>
      </td>
      <td>
        <%= form.number_field :quantity, in: 0.01..1000.0, step: 0.01, id: 'quantity-field', :oninput => 'updatePrice()', :autofocus => true %>
      </td>
    </tr>
    <tr class="total">
      <td colspan="3">
        Total: $
        <span id="total"><%= @purchaseOrder.coin.price %></span>
      </td>
    </tr>
    <tr>
      <td colspan="2">
      <td>
        <%= form.submit value="Buy"%>
      </td>
    </tr>
  </table>
  <%= fields_for :coin do |coin_form| %>
    <%= coin_form.hidden_field :id %>
    <%= coin_form.hidden_field :price %>
  <% end %>
<% end %>

app/views/purchase_orders/show.html.erb
<h1>Purchase Order # <%= @purchaseOrder.id %></h1>
<span class="purchase-order">
  <span class="coin">
      <span title="Coin Name">
        <%= @purchaseOrder.coin.coinName %>
      </span>
      <span title="Symbol">
        (<%= @purchaseOrder.coin.symbol %>)
      </span>
  </span>
  <span class="quantity" title="Quantity">
      x
      <%= @purchaseOrder.quantity %>
  </span>
  <span class="price">
    <span class="paid">
        <span class="label">Price paid</span>
        <span class="value">$ <%= @purchaseOrder.pricePaid %></span>
    </span>
    <span class="current">
        <span class="label">Current price</span>
        <span class="value <%= (@purchaseOrder.pricePaid > @purchaseOrder.priceNow)? 'lose' : 'win'  %>">$ <%= @purchaseOrder.priceNow %></span>
    </span>
  </span>
  <%= link_to 'Buy more', new_purchase_order_path(:coin_id => @purchaseOrder.coin.id) %>
</span>